import path from "path";
import glob from "fast-glob";
import type { Plugin, ViteDevServer } from "vite";

const MOCKUPS_DIR = "src/components/mockups";
const VIRTUAL_MODULE_ID = "virtual:mockup-components";
const RESOLVED_VIRTUAL_MODULE_ID = "\0" + VIRTUAL_MODULE_ID;

export function mockupPreviewPlugin(): Plugin {
  let root = "";
  let server: ViteDevServer | null = null;

  async function generateSource(): Promise<string> {
    const files = await glob(`${MOCKUPS_DIR}/**/*.tsx`, {
      cwd: root,
      ignore: ["**/_*/**", "**/_*.tsx"],
    });

    const entries = files
      .map((f) => {
        const globKey = "./" + f.slice("src/".length);
        const importPath = "/" + f;
        return `  ${JSON.stringify(globKey)}: () => import(${JSON.stringify(importPath)})`;
      })
      .join(",\n");

    return [
      "// This file is auto-generated by mockupPreviewPlugin.ts via Virtual Module.",
      "export const modules = {",
      entries,
      "};",
      "",
    ].join("\n");
  }

  return {
    name: "mockup-preview-virtual",
    enforce: "pre",

    configResolved(config) {
      root = config.root;
    },

    configureServer(viteServer) {
      server = viteServer;
      
      const mockupsAbsDir = path.join(root, MOCKUPS_DIR).split(path.sep).join('/');
      
      viteServer.watcher.on("add", (file) => {
        const normalizedFile = file.split(path.sep).join('/');
        if (normalizedFile.startsWith(mockupsAbsDir) && normalizedFile.endsWith(".tsx")) {
          const mod = server?.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
          if (mod) server?.moduleGraph.invalidateModule(mod);
        }
      });

      viteServer.watcher.on("unlink", (file) => {
        const normalizedFile = file.split(path.sep).join('/');
        if (normalizedFile.startsWith(mockupsAbsDir) && normalizedFile.endsWith(".tsx")) {
          const mod = server?.moduleGraph.getModuleById(RESOLVED_VIRTUAL_MODULE_ID);
          if (mod) server?.moduleGraph.invalidateModule(mod);
        }
      });
    },

    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
    },

    async load(id) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        return await generateSource();
      }
    },
  };
}
